#!/usr/bin/env bash
# Builds ONE paste-able SQL file from supabase/migrations/*.sql (the SAFE set: additive and re-runnable).
# Runs in a single transaction: if anything fails, nothing is applied. Review it, try it on a Supabase branch or after a
# backup, then paste it into the Supabase SQL editor. The cutover files are deliberately NOT included.
set -euo pipefail
cd "$(dirname "$0")/../.."
OUT=supabase/bundles/safe-migrations.sql
{
  echo "-- WASHO safe migrations bundle. Generated by supabase/bundles/build.sh. Do not edit: edit supabase/migrations/* and rebuild."
  echo "-- Additive and re-runnable. Single transaction. Does NOT include supabase/cutover/*."
  echo "BEGIN;"
  for f in supabase/migrations/*.sql; do
    echo; echo "-- ═════════════ $(basename "$f") ═════════════"
    cat "$f"
  done
  echo; echo "COMMIT;"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, $(ls supabase/migrations/*.sql | wc -l | tr -d ' ') migrations)"
